[package]
name = "layertuber"
version = "0.1.0"
edition = "2021"

[build-dependencies]
subprocess = "0.2.9"

[dependencies]
dirs = "4.0"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["serde_derive"] }
serde_json = "1.0"
subprocess = "0.2"
