on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install '.[dev]'
  mypy:
    needs: setup
    run: mypy
  flake8:
    needs: setup
    run: flake8
