on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install pygobject deps
        run: sudo apt install libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0
      - run: pip install '.[dev]'
  mypy:
    needs: setup
    run: mypy
  flake8:
    needs: setup
    run: flake8
